// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeI5-_eT6r7AaVRJPZvlEKN521H0x-yRk',
    appId: '1:759625472979:android:cf3840892bbc8e8c712d26',
    messagingSenderId: '759625472979',
    projectId: 'gymtracker-5404c',
    databaseURL: 'https://gymtracker-5404c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gymtracker-5404c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZdZ0AJBV-fQFwvWqItYbCTd9hjtz-T5c',
    appId: '1:759625472979:ios:7097d64d3fc6273a712d26',
    messagingSenderId: '759625472979',
    projectId: 'gymtracker-5404c',
    databaseURL: 'https://gymtracker-5404c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gymtracker-5404c.firebasestorage.app',
    androidClientId: '759625472979-co1087akgn1b3f3lfstjepsuoqrprc4g.apps.googleusercontent.com',
    iosClientId: '759625472979-jsj1m5pnhqbmthmoar68sklihr1bsq46.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymTrackerApp',
  );

}